import { useNavigate } from "react-router-dom";
import { ArrowLeft, Shield, AlertTriangle, FileText } from "lucide-react";

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div style={styles.page}>
      <button onClick={() => navigate(-1)} style={styles.back}>
        <ArrowLeft size={14} /> Back
      </button>

      <div style={styles.header}>
        <FileText size={28} color="#3B82F6" />
        <h1 style={styles.title}>Terms of Service</h1>
        <p style={styles.date}>Last updated: May 2025</p>
      </div>

      <div style={styles.disclaimer}>
        <AlertTriangle size={16} color="#F59E0B" />
        <p style={styles.disclaimerText}>
          <strong>IMPORTANT NOTICE:</strong> MySmartJournal is a personal trade logging and audit tool.
          It does not constitute financial advice. Trading involves substantial risk of loss.
        </p>
      </div>

      <div style={styles.content}>
        <Section title="1. Acceptance of Terms">
          <p>By accessing or using MySmartJournal, you agree to be bound by these Terms. If you do not agree to these terms, do not access or use the service.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>MySmartJournal is a SaaS trade journaling and audit platform designed for traders to record, review, and analyze their execution. The service includes:</p>
          <ul>
            <li>Personal trade logging and journaling</li>
            <li>Execution analytics and performance metrics</li>
            <li>AI-assisted trade feedback and audits</li>
            <li>Analytics and statistics dashboard</li>
          </ul>
        </Section>

        <Section title="3. Financial Risk Disclaimer" highlight>
          <p><strong>⚠️ MANDATORY FINANCIAL DISCLAIMER:</strong></p>
          <p>MySmartJournal <strong>DOES NOT provide financial advice</strong>. This service is strictly a trade journal and personal execution review tool.</p>
          <p>Analyses generated by artificial intelligence are provided for <strong>educational and informational purposes only</strong> and under no circumstances constitute:</p>
          <ul>
            <li>Investment recommendations or financial advice</li>
            <li>Trading signals or buy/sell suggestions</li>
            <li>Guarantees of profit or performance</li>
            <li>Personalized portfolio management</li>
          </ul>
          <p>Trading foreign exchange (Forex), stocks, commodities, crypto assets, and derivatives carries substantial risk of loss. Past performance is never indicative of future results.</p>
          <p><strong>"This tool does not provide financial advice. All trading involves risk of substantial loss."</strong></p>
        </Section>

        <Section title="4. User Accounts">
          <p>You are solely responsible for maintaining the confidentiality of your login credentials. You agree to:</p>
          <ul>
            <li>Provide accurate and complete information during registration</li>
            <li>Maintain the security and confidentiality of your credentials</li>
            <li>Notify us immediately of any unauthorized access or security breach</li>
          </ul>
        </Section>

        <Section title="5. Subscription and Billing">
          <p>MySmartJournal offers a free tier with core features and a Pro subscription at $7.99/month. Payments are securely processed via Stripe. Subscriptions renew automatically unless canceled prior to the billing date from Account Settings.</p>
        </Section>

        <Section title="6. Intellectual Property">
          <p>All software, brand elements, and UI designs are the exclusive property of MySmartJournal. Your logged trading data and personal journal entries remain 100% your property.</p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>MySmartJournal and its creators shall not be liable for any direct or indirect financial losses arising from your trading decisions or the use of AI audit insights. All trading is executed entirely at your own risk.</p>
        </Section>

        <Section title="8. Termination">
          <p>You may delete or cancel your account at any time from Settings. In the event of a violation of these Terms, we reserve the right to suspend or terminate your access.</p>
        </Section>

        <Section title="9. Contact">
          <p>For any inquiries: support@mysmartjournal.com</p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children, highlight }) {
  return (
    <div style={{ ...styles.section, backgroundColor: highlight ? "#451A0311" : "transparent", borderColor: highlight ? "#F59E0B33" : "#1E2D45", borderWidth: highlight ? "1px" : "0 0 1px 0" }}>
      <h2 style={styles.sectionTitle}>{title}</h2>
      <div style={styles.sectionContent}>{children}</div>
    </div>
  );
}

const styles = {
  page: { padding: "36px 32px", maxWidth: "800px", margin: "0 auto", fontFamily: "'Inter', sans-serif" },
  back: { display: "inline-flex", alignItems: "center", gap: "6px", backgroundColor: "transparent", border: "1px solid #1E2D45", borderRadius: "7px", color: "#6B7FA3", fontSize: "0.78rem", padding: "6px 12px", cursor: "pointer", fontFamily: "'Inter', sans-serif", marginBottom: "28px" },
  header: { display: "flex", flexDirection: "column", alignItems: "center", gap: "12px", marginBottom: "28px", textAlign: "center" },
  title: { fontSize: "1.8rem", fontWeight: "700", color: "#E8EDF5", margin: 0 },
  date: { color: "#6B7FA3", fontSize: "0.85rem", margin: 0 },
  disclaimer: { display: "flex", gap: "12px", alignItems: "flex-start", backgroundColor: "#451A0322", border: "1px solid #F59E0B44", borderRadius: "10px", padding: "16px 20px", marginBottom: "28px" },
  disclaimerText: { color: "#F59E0B", fontSize: "0.875rem", lineHeight: "1.6", margin: 0 },
  content: { display: "flex", flexDirection: "column", gap: "0" },
  section: { padding: "20px 0", borderStyle: "solid" },
  sectionTitle: { fontSize: "1rem", fontWeight: "700", color: "#E8EDF5", margin: "0 0 10px 0" },
  sectionContent: { color: "#94A3B8", fontSize: "0.875rem", lineHeight: "1.7" },
};