import { useNavigate } from "react-router-dom";
import { ArrowLeft, AlertTriangle } from "lucide-react";

export default function TradingDisclaimer() {
  const navigate = useNavigate();

  return (
    <div style={styles.page}>
      <button onClick={() => navigate(-1)} style={styles.back}>
        <ArrowLeft size={14} /> Back
      </button>

      <div style={styles.header}>
        <AlertTriangle size={32} color="#F59E0B" />
        <h1 style={styles.title}>Trading Risk Disclaimer</h1>
        <p style={styles.date}>Financial Risk & AI Audit Disclaimer</p>
      </div>

      <div style={styles.mainDisclaimer}>
        <p style={styles.mainText}>
          <strong>THIS TOOL DOES NOT PROVIDE FINANCIAL ADVICE.</strong>
        </p>
        <p style={styles.mainText}>
          MySmartJournal is a personal logging and trade journaling tool. All information, analyses, scores, and coaching prompts are provided strictly for <strong>educational and informational purposes only</strong>.
        </p>
      </div>

      <div style={styles.content}>
        <RiskSection title="Trading Risks">
          <p>Trading foreign exchange (Forex), equities, futures, options, crypto assets, and other leveraged financial instruments carries substantial risk of capital loss:</p>
          <ul>
            <li>You can lose some or all of your invested capital</li>
            <li>Trading on margin and leverage amplifies both potential profits and potential losses</li>
            <li>Past performance is never a guarantee or indicator of future results</li>
            <li>Financial markets are subject to extreme volatility, slippage, and liquidity shocks</li>
          </ul>
        </RiskSection>

        <RiskSection title="AI Model Limitations">
          <p>The analyses and scores generated by artificial intelligence in MySmartJournal:</p>
          <ul>
            <li>Are powered by statistical language models and do not represent accredited institutional advice</li>
            <li>Do not take into account your personal financial situation, risk tolerance, or account size</li>
            <li>May occasionally contain inaccuracies or incomplete market context</li>
            <li>Must never be used as the sole basis for executing, sizing, or exiting financial positions</li>
          </ul>
        </RiskSection>

        <RiskSection title="No Financial Advice">
          <p>MySmartJournal is NOT:</p>
          <ul>
            <li>A registered investment advisor, broker, or financial planner</li>
            <li>A portfolio management service</li>
            <li>A provider of regulated financial signals or trading calls</li>
          </ul>
          <p>If you require investment advice, consult a licensed, regulated financial professional in your jurisdiction.</p>
        </RiskSection>

        <RiskSection title="Trader Responsibility">
          <p>By using MySmartJournal, you explicitly acknowledge and agree that:</p>
          <ul>
            <li>You execute all trades entirely at your own discretion and risk</li>
            <li>MySmartJournal and its creators bear zero liability for any trading or capital losses</li>
            <li>You have read and fully understood this risk disclaimer</li>
            <li>You only risk capital that you can afford to lose</li>
          </ul>
        </RiskSection>
      </div>
    </div>
  );
}

function RiskSection({ title, children }) {
  return (
    <div style={styles.section}>
      <h2 style={styles.sectionTitle}>{title}</h2>
      <div style={styles.sectionContent}>{children}</div>
    </div>
  );
}

const styles = {
  page: { padding: "36px 32px", maxWidth: "800px", margin: "0 auto", fontFamily: "'Inter', sans-serif" },
  back: { display: "inline-flex", alignItems: "center", gap: "6px", backgroundColor: "transparent", border: "1px solid #1E2D45", borderRadius: "7px", color: "#6B7FA3", fontSize: "0.78rem", padding: "6px 12px", cursor: "pointer", fontFamily: "'Inter', sans-serif", marginBottom: "28px" },
  header: { display: "flex", flexDirection: "column", alignItems: "center", gap: "12px", marginBottom: "28px", textAlign: "center" },
  title: { fontSize: "1.8rem", fontWeight: "700", color: "#E8EDF5", margin: 0 },
  date: { color: "#6B7FA3", fontSize: "0.85rem", margin: 0 },
  mainDisclaimer: { backgroundColor: "#451A0322", border: "1px solid #F59E0B44", borderRadius: "10px", padding: "24px", marginBottom: "28px", textAlign: "center" },
  mainText: { color: "#F59E0B", fontSize: "1rem", lineHeight: "1.7", margin: "0 0 8px 0" },
  content: { display: "flex", flexDirection: "column" },
  section: { padding: "20px 0", borderBottom: "1px solid #1E2D45" },
  sectionTitle: { fontSize: "1rem", fontWeight: "700", color: "#E8EDF5", margin: "0 0 10px 0" },
  sectionContent: { color: "#94A3B8", fontSize: "0.875rem", lineHeight: "1.7" },
};